# Generated by Django 2.1.7 on 2019-08-03 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostFlie',
            new_name='PostFile',
        ),
    ]
